/* Build MARKET-VAULT from a single source.
 *
 *   price-tracker.html  ──┬──> deploy/index.html   (+ sw.js, manifest, icons, fonts)
 *                         └──> vault-mart.html     (standalone: everything inlined)
 *
 * Nothing in deploy/ is edited by hand and nothing there is committed — Vercel
 * runs this on every deploy, so a stale build is impossible.
 *
 *   node build.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, copyFileSync, rmSync } from "node:fs";
import { join } from "node:path";

const SRC = "price-tracker.html";
const OUT = "deploy";
const ASSETS = "assets";

const app = readFileSync(SRC, "utf8");
const version = (app.match(/APP_VERSION = "([^"]+)"/) || [])[1] || "0.0.0";

/* fail loudly rather than shipping a broken app */
const script = app.match(/<script>\s*"use strict"[\s\S]*?<\/script>/);
if (!script) throw new Error("could not find the main script block in " + SRC);
new Function(script[0].replace(/^<script>/, "").replace(/<\/script>$/, ""));

rmSync(OUT, { recursive: true, force: true });
mkdirSync(join(OUT, "fonts"), { recursive: true });

/* ---- 1. hosted build ---- */
writeFileSync(join(OUT, "index.html"), app);

for (const f of ["icon-192.png", "icon-512.png"]) copyFileSync(join(ASSETS, f), join(OUT, f));
const fonts = readdirSync(join(ASSETS, "fonts")).filter((f) => f.endsWith(".woff2"));
for (const f of fonts) copyFileSync(join(ASSETS, "fonts", f), join(OUT, "fonts", f));

writeFileSync(join(OUT, "manifest.webmanifest"), JSON.stringify({
  name: "MARKET-VAULT · מעקב מחירים",
  short_name: "MARKET-VAULT",
  lang: "he",
  dir: "rtl",
  start_url: "./",
  scope: "./",
  display: "standalone",
  orientation: "portrait",
  background_color: "#0b0f0a",
  theme_color: "#0b0f0a",
  icons: [
    { src: "./icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
    { src: "./icon-512.png", sizes: "512x512", type: "image/png", purpose: "any maskable" }
  ]
}, null, 2) + "\n");

/* the precache list is derived from the files actually present, so fonts can
   be added or removed without anyone remembering to edit the worker */
const precache = ["./", "./index.html", "./manifest.webmanifest", "./icon-192.png", "./icon-512.png"]
  .concat(fonts.map((f) => "./fonts/" + f));

writeFileSync(join(OUT, "sw.js"), `"use strict";
/* generated by build.mjs — do not edit */
var CACHE = "market-vault-${version}";
var ASSETS = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", function (ev) {
  ev.waitUntil(
    caches.open(CACHE).then(function (c) {
      return Promise.all(ASSETS.map(function (u) {
        return c.add(u).catch(function () { /* a missing asset must not fail install */ });
      }));
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function (ev) {
  ev.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function (ev) {
  var req = ev.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;

  /* the page is network-first so a redeploy lands on next load; assets are cache-first */
  var isDoc = req.mode === "navigate" || /\\.html$/.test(new URL(req.url).pathname);
  if (isDoc) {
    ev.respondWith(
      fetch(req).then(function (res) {
        if (res && res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        return caches.match(req).then(function (hit) { return hit || caches.match("./index.html"); });
      })
    );
    return;
  }

  ev.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        /* never hand the app shell to an <img>/<script>/manifest request */
        return Response.error();
      });
    })
  );
});
`);

/* ---- 2. standalone build ---- */
const icon = "data:image/png;base64," + readFileSync(join(ASSETS, "icon-192.png")).toString("base64");
const inlineManifest = "data:application/manifest+json," + encodeURIComponent(JSON.stringify({
  name: "MARKET-VAULT · מעקב מחירים",
  short_name: "MARKET-VAULT",
  lang: "he", dir: "rtl", display: "standalone",
  background_color: "#0b0f0a", theme_color: "#0b0f0a",
  icons: [{ src: icon, sizes: "192x192", type: "image/png" }]
}));

let standalone = app
  .replace('<link rel="manifest" href="./manifest.webmanifest">', `<link rel="manifest" href="${inlineManifest}">`)
  .replace('<link rel="apple-touch-icon" href="./icon-192.png">', `<link rel="apple-touch-icon" href="${icon}">`);

if (standalone.includes('href="./manifest.webmanifest"') || standalone.includes('href="./icon-192.png"'))
  throw new Error("standalone build still references external files");

writeFileSync("vault-mart.html", standalone);

console.log(`built v${version} → ${OUT}/ (${fonts.length} fonts) + vault-mart.html`);
